services:
  sandbox:
    image: tugboatqa/node:lts
    expose: 5000
    default: true
    commands:
      init:
        - yarn global add serve
      build:
        - yarn install --frozen-lockfile
        - yarn build
      start:
        - serve -s build
